config/routes.rb
Rails.application.routes.draw do
  # Auth users
  devise_for :users, controllers: { sessions: 'auth/sessions' }

  # API for SPA
  namespace :api do
    get 'skills', to: 'skills#list', format: false
    get 'resumes', to: 'resumes#list', format: false
    get 'vacancies', to: 'vacancies#list', format: false
  end

  #  Admin routes
  scope 'admin' do
    get '/', to: 'admin#index', as: 'admin_index', format: false
    resources :vacancies, format: false
    resources :resumes, format: false
  end

  # All roads lead to react SPA
  root to: 'index#index', as: 'home', format: false
  get '*path', to: 'index#index', format: false
end

app/models/vacancy.rb
# Vacancy model
class Vacancy < ApplicationRecord
  has_and_belongs_to_many :skills
  validates :email, email_format: { message: 'Формат: email@domain.org' }
  validates :price, presence: true, numericality: true
  validates :phone, presence: true, numericality: true
  validates :title, presence: true
  scope :full, lambda { |params|
    if params[:skills].present? && params[:full].present? && params[:full] == 'true'
      q = format 'SELECT "vacancies"."id" FROM "vacancies"
            INNER JOIN "skills_vacancies" ON "skills_vacancies"."vacancy_id" = "vacancies"."id"
            GROUP BY "vacancies"."id"
            HAVING (COUNT(DISTINCT skill_id) = %s)', params[:skills].size

      where("vacancies.id in (#{q})")
    end
  }
  scope :skills, ->(params) { where(skills: { id: params[:skills] }) if params[:skills].present? }
  scope :valid, ->(params) { where('valid_before > ?', DateTime.now) if params[:valid].present? }
  default_scope { includes(:skills).order('price DESC') }

  def valid_before
    if self[:valid_before].nil?
      self[:valid_before]
    else
      self[:valid_before].strftime('%d-%m-%Y')
    end
  end

  def created_at
    self[:created_at].strftime('%d-%m-%Y')
  end
end

app/controllers/api/vacancies_controller.rb
module Api
  # Vacancies API controller
  class VacanciesController < ApplicationController
    def list
      @vacancies = VacancyBuilder.new(params).resolve

      render json: @vacancies.to_json(include: :skills)
    end
  end
end

app/controllers/vacancies_controller.rb
# Vacncoes Controller
class VacanciesController < AdminController
  before_action :set_vacancy, only: [:show, :edit, :update, :destroy]
  before_action :new_vacancy, only: [:create, :new]
  before_action :set_skill_ids, only: [:create, :update]

  # GET /vacancies
  def index
    @vacancies = Vacancy.all
  end

  # GET /vacancies/1
  def show; end

  # GET /vacancies/new
  def new; end

  # GET /vacancies/1/edit
  def edit; end

  # POST /vacancies
  def create
    if @vacancy.save
      redirect_to edit_vacancy_path(@vacancy.id), notice: 'Вакансия была создана.'
    else
      render :new
    end
  end

  # PATCH/PUT /vacancies/1
  def update
    if @vacancy.update(vacancy_params)
      redirect_to edit_vacancy_path(@vacancy.id), notice: 'Вакансия была обновлена.'
    else
      render :edit
    end
  end

  # DELETE /vacancies/1
  def destroy
    @vacancy.destroy

    redirect_to vacancies_url, notice: 'Вакансия была удалена.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vacancy
    @vacancy = Vacancy.find(params[:id])
  end

  def new_vacancy
    @vacancy = Vacancy.new(vacancy_params)
  end

  # Find and create skills for vacancy
  def set_skill_ids
    @vacancy.skill_ids = SkillGenerator.new(params.fetch(:vacancy, {})[:skill_ids]).generate
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vacancy_params
    params.fetch(:vacancy, {}).permit(:title, :phone, :price, :email, :organization, :valid_before, :skill_ids)
  end
end

app/helpers/api/vacancies_helper.rb
module Api
  # Vacancies helper
  module VacanciesHelper
  end
end

app/helpers/vacancies_helper.rb
# Vacancies controller helper
module VacanciesHelper
end

app/views/vacancies/_form.html.slim
p#notice = notice
= form_for @vacancy do |f|
  - if @vacancy.errors.any?
    #error_explanation
      h3 = "При сохранении возниклки ошибки:"
      ul
        - @vacancy.errors.full_messages.each do |message|
          li = message

  .col-md-6
    .row
      .form-group.col-md-12
        .col-md-3
          = 'Название: '
        .col-md-6
          = f.text_field :title, class: 'form-control'

      .form-group.col-md-12
        .col-md-3
          = 'Зарплата: '
        .col-md-6
          = f.text_field :price, class: 'form-control'

      .form-group.col-md-12
        .col-md-3
          = 'Телефон: '
        .col-md-6
          = f.text_field :phone, class: 'form-control'

      .form-group.col-md-12
        .col-md-3
          = 'Email: '
        .col-md-6
          = f.text_field :email, class: 'form-control'

      .form-group.col-md-12
        .col-md-3
          = 'Организация: '
        .col-md-6
          = f.text_field :organization, class: 'form-control'
      .form-group.col-md-12
        .col-md-3
          = 'Актуально до: '
        .col-md-6
          = f.text_field :valid_before, class: 'form-control datepicker', data: { provide: 'datepicker', date_format: 'dd-mm-yyyy' }

      .form-group.col-md-12
        .col-md-3
          = 'Навыки: '
        .col-md-6
          = f.collection_select :skill_ids, Skill.all, :title, :title, {selected: @vacancy.skills.pluck(:title)}, {multiple: true, class: "form-control js-example-tags"}

      .form-group.col-md-12
        .col-md-3
          = f.submit class: 'btn btn-success'
        .col-md-4
        .col-md-3
          = link_to 'Назад', vacancies_path, class: 'btn btn-default'

app/views/vacancies/edit.html.slim
.col-md-12
  h1 Редактировать вакансию #{@vacancy.id}

  == render 'form'

app/views/vacancies/index.html.slim
.col-md-12
  h1 Вакансии

  = link_to 'Новая вакансия', new_vacancy_path, class: 'btn btn-default'

  table.table
    thead
      tr
        th
          = 'Название'
        th
          = 'Создана'
        th
          = 'Актуальна до'
        th
          = 'Зарплата'
        th
          = 'Контакты'
        th
          = 'Действия'

    tbody
      - @vacancies.each do |vacancy|
        tr
          td
            = vacancy.title
          td
            = vacancy.created_at
          td
            = vacancy.valid_before
          td
            = vacancy.price
          td
            = vacancy.email
            br
            = vacancy.phone
            br
            = vacancy.organization
          td 
            = link_to 'Edit', edit_vacancy_path(vacancy), class: 'btn btn-info'
            br
            = link_to 'Destroy', vacancy, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'

app/views/vacancies/new.html.slim
.col-md-12
  h1 Новая вакансия

  == render 'form'

app/views/vacancies/show.html.slim
p#notice = notice


= link_to 'Редактировать', edit_vacancy_path(@vacancy)
'  |
= link_to 'Назад', vacancies_path