config/routes.rb
Rails.application.routes.draw do
  # Auth users
  devise_for :users, controllers: { sessions: 'auth/sessions' }

  # API for SPA
  namespace :api do
    get 'skills', to: 'skills#list', format: false
    get 'resumes', to: 'resumes#list', format: false
    get 'vacancies', to: 'vacancies#list', format: false
  end

  #  Admin routes
  scope 'admin' do
    get '/', to: 'admin#index', as: 'admin_index', format: false
    resources :vacancies, format: false
    resources :resumes, format: false
  end

  # All roads lead to react SPA
  root to: 'index#index', as: 'home', format: false
  get '*path', to: 'index#index', format: false
end

app/models/resume.rb
# Resume model
class Resume < ApplicationRecord
  has_and_belongs_to_many :skills
  validates :name, format: { with: /\A[а-яА-Я]+ [а-яА-Я]+ [а-яА-Я]+\z/, message: 'Формат ввода: Фамилия Имя Отчество' }
  validates :email, email_format: { message: 'Формат: email@domain.org' }
  validates :price, presence: true, numericality: true
  validates :phone, presence: true, numericality: true
  scope :full, lambda { |params|
    if params[:skills].present? && params[:full].present? && params[:full] == 'true'
      q = format 'SELECT "resumes"."id" FROM "resumes"
          INNER JOIN "resumes_skills" ON "resumes_skills"."resume_id" = "resumes"."id"
          GROUP BY "resumes"."id"
          HAVING (COUNT(DISTINCT skill_id) = %s)', params[:skills].size

      where("resumes.id in (#{q})")
    end
  }
  scope :position, lambda { |params|
    if params[:position].present?
      q = format 'SELECT "skills_vacancies"."skill_id" as id FROM "vacancies"
            INNER JOIN "skills_vacancies" ON "skills_vacancies"."vacancy_id" = "vacancies"."id"
            WHERE "vacancies"."id" = %s', params[:position].to_i
      joins(:skills).where("skills.id in (#{q})")
    end
  }
  scope :skills, ->(params) { where(skills: { id: params[:skills] }) if params[:skills].present? }
  scope :active, ->(params) { where(status: true) if params[:active].present? }
  default_scope { includes(:skills).order('price DESC') }
end

app/controllers/api/resumes_controller.rb
module Api
  # Resumes API controller
  class ResumesController < ApplicationController
    def list
      @resumes = ResumeBuilder.new(params).resolve

      render json: @resumes.to_json(include: :skills)
    end
  end
end

app/controllers/resumes_controller.rb
# Resume Controller
class ResumesController < AdminController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]
  before_action :new_resume, only: [:create, :new]
  before_action :set_skill_ids, only: [:create, :update]

  # GET /resumes
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  def show; end

  # GET /resumes/new
  def new; end

  # GET /resumes/1/edit
  def edit; end

  # POST /resumes
  def create
    if @resume.save
      redirect_to edit_resume_path(@resume.id), notice: 'Резюме было создано.'
    else
      render :new
    end
  end

  # PATCH/PUT /resumes/1
  def update
    if @resume.update(resume_params)
      redirect_to edit_resume_path(@resume.id), notice: 'Резюме было обновлено.'
    else
      render :edit
    end
  end

  # DELETE /resumes/1
  def destroy
    @resume.destroy

    redirect_to resumes_url, notice: 'Резюме было удалено.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_resume
    @resume = Resume.find(params[:id])
  end

  def new_resume
    @resume = Resume.new(resume_params)
  end

  # Find and create skills for vacancy
  def set_skill_ids
    @resume.skill_ids = SkillGenerator.new(params.fetch(:resume, {})[:skill_ids]).generate
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def resume_params
    params.fetch(:resume, {}).permit(:name, :phone, :price, :email, :status, :skill_ids)
  end
end

app/helpers/api/resumes_helper.rb
module Api
  # Resume helper
  module ResumesHelper
  end
end

app/helpers/resumes_helper.rb
# Resumes controller helper
module ResumesHelper
end

app/views/resumes/_form.html.slim
p#notice = notice
= form_for @resume do |f|
  - if @resume.errors.any?
    #error_explanation
      h3 = "При сохранении возниклки ошибки:"
      ul
        - @resume.errors.full_messages.each do |message|
          li = message

  .col-md-6
    .row
      .form-group.col-md-12
        .col-md-3
          = 'Имя: '
        .col-md-6
          = f.text_field :name, class: 'form-control'

      .form-group.col-md-12
        .col-md-3
          = 'Зарплата: '
        .col-md-6
          = f.text_field :price, class: 'form-control'

      .form-group.col-md-12
        .col-md-3
          = 'Email: '
        .col-md-6
          = f.text_field :email, class: 'form-control'

      .form-group.col-md-12
        .col-md-3
          = 'Телефон: '
        .col-md-6
          = f.text_field :phone, class: 'form-control'

      .form-group.col-md-12
        .col-md-3
          = 'Статус: '
        .col-md-6
          .checkbox
            = f.label :status
              = f.check_box :status, class: 'checkbox'
              = 'Актуальное резюме'

      .form-group.col-md-12
        .col-md-3
          = 'Навыки: '
        .col-md-6
          = f.collection_select :skill_ids, Skill.all, :title, :title, {selected: @resume.skills.pluck(:title)}, { multiple: true, class: "form-control js-example-tags" }

      .form-group.col-md-12
        .col-md-3
          = f.submit class: 'btn btn-success'
        .col-md-4
        .col-md-3
          = link_to 'Назад', resumes_path, class: 'btn btn-default'

app/views/resumes/edit.html.slim
.col-md-12
  h1 Редактировать резюме #{@resume.id}

  == render 'form'

app/views/resumes/index.html.slim
.col-md-12
  h1 Резюме

  = link_to 'Новое резюме', new_resume_path, class: 'btn btn-default'

  table.table
    thead
      tr
        th
          = 'Имя'
        th
          = 'Статус'
        th
          = 'Зарплата'
        th
          = 'Контакты'
        th
          = 'Действия'

    tbody
      - @resumes.each do |resume|
        tr
          td
            = resume.name
          td
            = resume.status
          td
            = resume.price
          td
            = resume.email
            br
            = resume.phone
          td 
            = link_to 'Edit', edit_resume_path(resume), class: 'btn btn-info'
            br
            = link_to 'Destroy', resume, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'

app/views/resumes/new.html.slim
.col-md-12
  h1 Новое резюме

  == render 'form'

app/views/resumes/show.html.slim
p#notice = notice


= link_to 'Редактировать', edit_resume_path(@resume)
'  |
= link_to 'Назад', resumes_path